# Generated by Django 2.0.6 on 2018-06-07 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doubloon', '0002_auto_20180606_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trendmodel',
            old_name='deprecation',
            new_name='depreciation',
        ),
        migrations.RenameField(
            model_name='trendmodel',
            old_name='deprecation_rate',
            new_name='depreciation_rate',
        ),
    ]
