# Generated by Django 2.0.6 on 2018-07-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubloon', '0004_auto_20180606_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForcedSell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=100)),
                ('uuid', models.CharField(max_length=400)),
                ('closed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Forced Sell',
                'verbose_name_plural': 'Forced Sells',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=100)),
                ('base_currency', models.CharField(max_length=100)),
                ('base_cost', models.FloatField()),
                ('base_earned', models.FloatField(blank=True, default=None, null=True)),
                ('market_currency', models.CharField(max_length=100)),
                ('market_quantity', models.FloatField()),
                ('market_buy_price', models.FloatField()),
                ('market_sell_price', models.FloatField(blank=True, default=None, null=True)),
                ('gain_loss', models.FloatField(blank=True, default=None, null=True)),
                ('opened', models.DateTimeField()),
                ('closed', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='TradeMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('tick_interval', models.CharField(max_length=32)),
                ('long_sma_period', models.IntegerField()),
                ('short_sma_period', models.IntegerField()),
                ('ema_period', models.IntegerField()),
                ('total_top_markets', models.IntegerField()),
                ('minimum_gain_for_sell', models.FloatField()),
            ],
            options={
                'verbose_name': 'Trade Metric',
                'verbose_name_plural': 'Trade Metrics',
            },
        ),
        migrations.DeleteModel(
            name='Currencies',
        ),
        migrations.DeleteModel(
            name='CurrentValues',
        ),
        migrations.DeleteModel(
            name='Logs',
        ),
        migrations.DeleteModel(
            name='PatternPriority',
        ),
        migrations.DeleteModel(
            name='PurchaseHistory',
        ),
        migrations.DeleteModel(
            name='Statistics',
        ),
        migrations.DeleteModel(
            name='TrendModel',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
        migrations.AlterField(
            model_name='settings',
            name='setting',
            field=models.CharField(max_length=256),
        ),
    ]
