# Generated by Django 2.0.6 on 2018-07-12 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doubloon', '0005_auto_20180712_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forcedsell',
            name='closed',
        ),
    ]
