# Generated by Django 2.0.6 on 2018-07-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubloon', '0006_remove_forcedsell_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='closed',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
