# Generated by Django 2.0.6 on 2018-12-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubloon', '0008_lastanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastanalysis',
            name='reasons',
            field=models.TextField(default=[]),
            preserve_default=False,
        ),
    ]
