# Generated by Django 2.0.6 on 2018-12-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubloon', '0009_lastanalysis_reasons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('match_list', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Ranks',
                'verbose_name': 'Rank',
            },
        ),
        migrations.AddField(
            model_name='trademetrics',
            name='ranks',
            field=models.TextField(default=[]),
            preserve_default=False,
        ),
    ]
